config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :documents do
    resources :permissions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user

  has_many :permissions, dependent: :destroy
  has_many :operations, dependent: :destroy

  def apply_changes(operation)
    if operation.kind == 'insert'
      content.insert(operation.data['offset'], operation.data['text'])
    elsif operation.kind == 'remove'
      content.slice!(operation.data['offset'], operation.data['text'].length)
    end

    self.version = operation.version + 1

    self
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :document

  serialize :data, JSON

  validates :document_id, presence: true

  # There's only one version of data
  validates :version, presence: true, uniqueness: { scope: :document_id }
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :document
  belongs_to :user

  class Role < Enum
    WRITER = 'writer'
    READER = 'reader'
  end

  attribute :role,:string, default: Role::WRITER
  validates :role, inclusion: { in: Role.values }

  def writer?
    role == Role::WRITER
  end

  def reader?
    role == Role::READER
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :documents, dependent: :destroy
  has_many :permissions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  include Pundit
  protect_from_forgery

  after_action :verify_authorized, except: %i[index new create]
  after_action :verify_policy_scoped, only: :index

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < BaseController
  before_action :set_record, only: %i[show edit update destroy]

  # GET documents
  def index
    @documents = scope
  end

  # GET documents/1
  def show
    authorize @document

    @document
  end

  # GET documents/new
  def new
    @document = Document.new
  end

  # POST documents
  def create
    # FIXME: change default to ''
    title = secure_params[:title].present? ? secure_params[:title] : ''
    content = secure_params[:content].present? ? secure_params[:content] : ''

    @document = current_user.documents.create!({ title: title, content: content })

    redirect_to @document
  end

  # GET documents/1/edit
  def edit
    authorize @document

    @document
  end

  # PATCH/PUT documents/1
  def update
    authorize @document

    @document.update!(secure_params)

    redirect_to @document
  end

  # DELETE documents/1
  def destroy
    authorize @document

    @document.destroy!

    redirect_to documents_path
  end

  private

  def secure_params
    params.require(:document)
          .permit(:title, :content)
  end

  def scope
    policy_scope(Document)
  end

  def set_record
    @document = Document.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < BaseController
  def index
    skip_authorization
    skip_policy_scope
  end
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  before_action :set_permission, only: %i[show edit update destroy]
  before_action :set_document

  # FIXME: before_create/update should verify
  #   if there's already a permission on this doc for this user

  # GET documents/1/permissions
  def index
    @permissions = Permission.where(document: @document)
  end

  # GET documents/1/permissions/new
  def new
    @permission = Permission.new
  end

  # POST documents/1/permissions
  def create
    # FIXME: If cannot find, should create User and sent invitation
    #   e.g FindOrInviteUserService
    user = User.find_by(email: secure_params[:user][:email])

    @permission = Permission.new(
      document: @document,
      user: user,
      role: secure_params[:role]
    )

    if @permission.save
      redirect_to document_permissions_path
    else
      redirect_to document_permissions_path, notice: 'Something went wrong.'
    end
  end

  # GET documents/1/permissions/1/edit
  def edit
    @document
  end

  # PATCH/PUT documents/1/permissions/1
  def update
    # FIXME: If cannot find, should create User and sent invitation
    #   e.g FindOrInviteUserService
    user = User.find_by(email: secure_params[:user][:email])

    if @permission.update(user: user, role: secure_params[:role])
      redirect_to document_permissions_path
    else
      redirect_to document_permissions_path, notice: 'Something went wrong.'
    end
  end

  # DELETE documents/1/permissions/1
  def destroy
    @permission.destroy!

    redirect_to document_permissions_path
  end

  private

  def secure_params
    params.require(:permission).permit(:role, user: [:email])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_permission
    @permission = Permission.includes(:user).find(params[:id])
  end

  def set_document
    @document = Document.find(params[:document_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/documents/_form.html.erb
<%= form_with model: @document do |form| %>
  <div class="my-4">
    <div class="input-group">
      <%= form.text_field :title, class: "form-control" %>

      <div class="input-group-append">
        <%= form.submit "Save Title", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/documents/edit.html.erb
<%= render 'form' %>

<%= content_tag :div,
  class: "collaborative-editor",
  data: {
    client: current_user,
    documentId: @document.id,
    content: @document.content,
    version: @document.version
  }.to_json do %><% end %>

<%= link_to 'Back', documents_path, class: "btn btn-link" %>

app/views/documents/index.html.erb
<div class="d-flex justify-content-between align-items-center my-4">
  <h2>Documents</h2>

  <%= link_to 'New document', new_document_path, class: "btn btn-primary ml-auto" %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Owner</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
  <% @documents.each do |document| %>
    <tr>
      <th scope="row"><%= document.title %></th>
      <th scope="row"><%= document.user.email %></th>
      <th scope="row">
        <% if DocumentPolicy.new(current_user, document).update_permissions? %>
          <%= link_to 'Permissions', document_permissions_path(document), class: "btn btn-link" %>
        <% end %>

        <% if DocumentPolicy.new(current_user, document).show? %>
          <%= link_to 'Show', document_path(document), class: "btn btn-link" %>
        <% end %>

        <% if DocumentPolicy.new(current_user, document).update? %>
          <%= link_to 'Edit', edit_document_path(document), class: "btn btn-link" %>
        <% end %>

        <% if DocumentPolicy.new(current_user, document).destroy? %>
          <%= link_to 'Destroy', document_path(document), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
        <% end %>
      </th>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/documents/new.html.erb
<div class="d-flex justify-content-between align-items-center my-4">
  <h2>New document</h2>

  <%= link_to 'Back', documents_path, class: "btn btn-link ml-auto" %>
</div>

<%= render 'form' %>

<%= link_to 'Back', documents_path, class: "btn btn-link" %>

app/views/documents/show.html.erb
<div class="d-flex justify-content-between align-items-center my-4">
  <h2><%= @document.title %></h2>

  <%= link_to 'Back', documents_path, class: "btn btn-link ml-auto" %>
</div>

<div class="card my-4">
  <pre class="prettyprint"><%= @document.content %></pre>
</div>

<%= link_to 'Edit', edit_document_path(@document), class: "btn btn-link" %>
<%= link_to 'Back', documents_path, class: "btn btn-link" %>

app/views/home/index.html.erb
<p>Logged in as <strong><%= current_user.email %></strong>.</p>

<p>Welcome to codecrew, a pair programming platform where you can share documents between colleagues and work together!</p>

<%= link_to 'Start pairing now!', new_document_path, class: "btn btn-primary" %>

app/views/layouts/_alerts.html.erb
<div class="container alerts">
  <% if notice %>
    <p class="notice alert alert-warning" role="alert">
      <%= notice %>
    </p>
  <% end %>

  <% if alert %>
    <p class="alert alert-danger" role="alert">
      <%= alert %>
    </p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">
    <%= image_tag image_url('text_white_with_dino.png'), height: "30" %>
  </a>

  <div class="collapse navbar-collapse">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Documents', documents_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_url, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeCrew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
  </head>

  <body class="app <%= 'bg-primary' unless user_signed_in? %>">
    <% if user_signed_in? %>
      <%= render 'layouts/navbar' %>
    <% end %>

    <div class="container my-4">
      <%= yield %>
    </div>

    <%= render 'layouts/alerts' %>
  </body>
</html>

app/views/permissions/edit.html.erb
<h2>Editing Permission</h2>

<%= form_with model: @permission, url: document_permission_path, multiple: true do |form| %>
  <%= form.fields_for :user, @permission.user do |user| %>
    <p class="form-group">
      <%= user.text_field :email, class: "form-control" %>
    </p>
  <% end %>

  <p class="form-group">
    <%= form.label :role %><br>
    <%= form.select :role, [%w(Writer writer), %w(Reader reader)], {}, { class: "form-control" } %>
  </p>

  <p class="form-group actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </p>
<% end %>

<%= link_to 'Back', document_permissions_path %>

app/views/permissions/index.html.erb
<div class="d-flex justify-content-between align-items-center my-4">
  <h2>Permissions</h2>
  <%= link_to 'Add permission', new_document_permission_path, class: "btn btn-primary ml-auto" %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">User</th>
      <th scope="col">Role</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
  <% @permissions.each do |permission| %>
    <tr>
      <th scope="row"><%= permission.user.email %></th>
      <th scope="row"><%= permission.role %></th>
      <td>
        <%= link_to 'Edit', edit_document_permission_path(@document, permission), class: "btn btn-link" %>
        <%= link_to 'Remove', document_permission_path(@document, permission), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', documents_path, class: "btn btn-link" %>

app/views/permissions/new.html.erb
<h2>New Permission</h2>

<%= form_with model: @permission, url: document_permissions_path, multiple: true do |form| %>
  <%= form.fields_for :user, @permission.user do |user| %>
    <p class="form-group">
      <%= user.text_field :email, class: "form-control" %>
    </p>
  <% end %>

  <p class="form-group">
    <%= form.label :role %><br>
    <%= form.select :role, [%w(Writer writer), %w(Reader reader)], {}, { class: "form-control" } %>
  </p>

  <p class="form-group actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </p>
<% end %>

<%= link_to 'Back', document_permissions_path %>